WITH SALE AS (
SELECT SALES_DATE
    , PRODUCT_ID
    , USER_ID
    , SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
UNION ALL
SELECT SALES_DATE
    , PRODUCT_ID
    , NULL AS USER_ID
    , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
)
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE,
       PRODUCT_ID,
       USER_ID,
       SALES_AMOUNT
  FROM SALE
 ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
