-- 코드를 입력하세요
WITH A AS(
    SELECT ANIMAL_ID,ANIMAL_TYPE,NAME,SEX_UPON_INTAKE
      FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE '%Intact%'
)
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
  FROM A INNER JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
 WHERE B.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
 ORDER BY B.ANIMAL_ID
