-- 코드를 입력하세요

SELECT A.FLAVOR
  FROM FIRST_HALF A INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
 FROM JULY
 GROUP BY FLAVOR ) B
 ON A.FLAVOR = B.FLAVOR 
 ORDER BY TOTAL_ORDER + JULY_ORDER DESC
 LIMIT 3


