WITH MAX_S AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE
            , YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR )
    
    
    
SELECT M.YEAR
        , (M.MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV
        , E.ID
FROM MAX_S M INNER JOIN  ECOLI_DATA E
                    ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
WHERE YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR, YEAR_DEV