WITH FISH_MAX AS (
    SELECT MAX(LENGTH) MAX_LENGTH, FISH_TYPE
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
)
SELECT I.ID, N.FISH_NAME, M.MAX_LENGTH LENGTH
FROM 
FISH_MAX M 
JOIN 
FISH_INFO I
ON M.FISH_TYPE = I.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH 
JOIN 
FISH_NAME_INFO N 
ON N.FISH_TYPE = M.FISH_TYPE
ORDER BY I.ID
