WITH MAX_VIEWS AS (
SELECT  BOARD_ID
  FROM USED_GOODS_BOARD
 ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
  FROM USED_GOODS_FILE A
 WHERE A.BOARD_ID = (SELECT BOARD_ID FROM MAX_VIEWS)
 ORDER BY FILE_ID DESC
